const listings = [
  {id:'p1',name:'محمد علي',sub:'مترجم ومرافق أعمال',city:'نيودلهي، الهند',cat:'ترجمة',rating:'4.9',reviews:126,verified:true,price:45,distance:null,image:'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=500',about:'مترجم عربي وإنجليزي وهندي، أساعد الزوار والطلاب ورجال الأعمال في نيودلهي منذ 8 سنوات.',langs:'العربية • English • हिन्दी',type:'person'},
  {id:'b1',name:'باب اليمن',sub:'مطعم يمني أصيل',city:'الرياض، السعودية',cat:'مطاعم',rating:'4.8',reviews:842,verified:true,price:null,distance:.8,image:'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500',about:'مندي ومظبي وسلتة بنكهات يمنية أصيلة، وجلسات عائلية هادئة.',langs:'العربية • English',type:'business'},
  {id:'p2',name:'سالم القباطي',sub:'سائق واستقبال مطار',city:'كوالالمبور، ماليزيا',cat:'نقل',rating:'4.9',reviews:203,verified:true,price:30,distance:3.2,image:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500',about:'استقبال من المطار وجولات خاصة للعائلات والطلاب داخل كوالالمبور.',langs:'العربية • English • Malay',type:'person'},
  {id:'b2',name:'سكن روافد الطلاب',sub:'سكن طلاب قريب من الجامعة',city:'كوالالمبور، ماليزيا',cat:'سكن',rating:'4.7',reviews:91,verified:true,price:180,distance:null,image:'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=500',about:'غرف مفروشة وخدمة استقبال ومساعدة للطلاب اليمنيين الجدد.',langs:'العربية • English',type:'business'},
  {id:'p3',name:'أروى الحكيمي',sub:'مصورة فعاليات وفيديو',city:'الرياض، السعودية',cat:'تصوير',rating:'4.9',reviews:74,verified:true,price:650,distance:5.1,image:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500',about:'تغطية فعاليات ومناسبات وإنتاج فيديو قصير باحترافية وخصوصية.',langs:'العربية • English',type:'person'},
  {id:'b3',name:'سبأ للشحن الدولي',sub:'شحن طرود وبضائع إلى اليمن',city:'نيويورك، أمريكا',cat:'شحن',rating:'4.6',reviews:318,verified:true,price:null,distance:1.4,image:'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=500',about:'حلول شحن جوي وبحري وتتبع للطرود من الولايات المتحدة إلى اليمن.',langs:'العربية • English',type:'business'}
];
const categories = [['文','ترجمة'],['☕','مطاعم'],['↗','نقل'],['▣','شحن'],['⌂','سكن'],['●','تصوير'],['◆','عسل'],['</>','تقنية']];
const requests = [
  {id:'r1',title:'أحتاج مصورًا في الرياض',desc:'تغطية فعالية يوم الجمعة من 6 إلى 10 مساءً.',place:'الرياض، السعودية',offers:3,budget:1200,time:'منذ 18 دقيقة'},
  {id:'r2',title:'مترجم في نيودلهي',desc:'مرافق لمدة يومين لمواعيد عمل.',place:'نيودلهي، الهند',offers:5,budget:180,time:'منذ ساعة'},
  {id:'r3',title:'سكن طالب لمدة شهر',desc:'غرفة قريبة من المواصلات ابتداء من أكتوبر.',place:'كوالالمبور، ماليزيا',offers:8,budget:null,time:'منذ 3 ساعات'}
];
const state = {screen:'onboarding',saved:new Set(),map:false,signed:false,query:'',category:''};
const app = document.querySelector('#app');

function go(screen, data={}) { state.screen=screen; Object.assign(state,data); render(); window.scrollTo({top:0,behavior:'smooth'}); }
function toast(text){ const el=document.createElement('div'); el.className='toast'; el.textContent=text; document.body.append(el); setTimeout(()=>el.remove(),2100); }
function topbar(title, back=false){ return `<header class="topbar">${back?`<button class="icon-btn" onclick="historyBack()" aria-label="رجوع">←</button>`:''}<div class="brand">${back?'':`<span class="mark">ي</span>`}<span>${title}</span></div><button class="icon-btn" onclick="go('notifications')" aria-label="الإشعارات">♢</button></header>`; }
function nav(active){ return `<nav class="bottom">${[['home','⌂','الرئيسية'],['search','⌕','استكشف'],['add','+','إضافة'],['requests','▤','الطلبات'],['account','○','حسابي']].map(([id,ico,label])=>`<button class="nav ${id===active?'active':''} ${id==='add'?'add':''}" onclick="${id==='add'?"go('newRequest')":`go('${id}')`}"><b>${ico}</b><span>${label}</span></button>`).join('')}</nav>`; }
function historyBack(){ go(state.screen==='detail'?'search':'home'); }
function listingCard(x){ const saved=state.saved.has(x.id); return `<article class="listing" onclick="go('detail',{selected:'${x.id}'})"><img src="${x.image}" alt=""><div class="listing-main"><h3>${x.name} ${x.verified?'<span class="verified">✓</span>':''}</h3><p>${x.sub}</p><div class="meta"><span class="rating">★ ${x.rating} (${x.reviews})</span><span>⌖ ${x.city}</span>${x.distance?`<span>◉ ${x.distance} كم</span>`:''}</div>${x.price?`<div class="price">يبدأ من ${x.price} USD</div>`:''}</div><button class="save" aria-label="حفظ" onclick="event.stopPropagation();toggleSave('${x.id}')">${saved?'♥':'♡'}</button></article>`; }
function toggleSave(id){ if(!state.signed){ go('account'); toast('سجّل الدخول أولًا للحفظ'); return;} state.saved.has(id)?state.saved.delete(id):state.saved.add(id); render(); }
function render(){ app.innerHTML=`<div class="app">${screens[state.screen]()}</div>`; }

const screens = {
  onboarding:()=>`<section class="onboarding"><div class="onboarding-top"><span class="mark" style="background:#ffffff10;border:1px solid #ffffff20;color:#e3c088;border-radius:14px">ي</span><button class="lang" onclick="toast('English preview is included in the Flutter app')">عربي / EN</button></div><div class="onboarding-copy"><h1>يمني حول العالم</h1><p style="color:#d8e3e9;font-weight:700;margin-bottom:5px">من اليمن إلى كل العالم</p><p>مجتمع واحد، خدمات أقرب، وهوية تجمعنا أينما كنا.</p><div class="notice"><span>◎</span> أشخاص، منشآت، خدمات وفرص يمنية حول العالم</div></div><button class="primary" onclick="go('home')">ابدأ الاستكشاف</button><button style="margin-top:8px;background:transparent;border:0;color:#c6d2d9;padding:12px;font-weight:800" onclick="go('account')">تسجيل الدخول</button></section>`,
  home:()=>`<section class="screen">${topbar('يمني حول العالم')}<div class="pad"><button class="location" onclick="go('search')">⌖ الرياض، السعودية⌄</button><div class="search" onclick="go('search')"><span>⌕</span><input readonly placeholder="ماذا تبحث عنه؟"><span>☷</span></div><div class="quick-grid"><button class="quick" onclick="go('nearby')"><span class="ico">◉</span><span><strong>قريب مني</strong><small>حسب المسافة</small></span></button><button class="quick" onclick="go('offers')"><span class="ico">◇</span><span><strong>عروض اليوم</strong><small>وفر أكثر</small></span></button></div><div class="section-head"><h2>التصنيفات</h2><button class="link" onclick="go('search')">عرض الكل</button></div></div><div class="categories">${categories.map(c=>`<button class="cat" onclick="go('search',{category:'${c[1]}'})"><span class="cat-icon">${c[0]}</span><span>${c[1]}</span></button>`).join('')}</div><div class="pad"><div class="section-head"><h2>موصى به لك</h2><button class="link" onclick="go('search')">استكشف</button></div>${listings.slice(0,3).map(listingCard).join('')}<div class="section-head"><h2>طلبات حديثة</h2><button class="link" onclick="go('requests')">عرض الكل</button></div>${requests.slice(0,2).map(r=>`<div class="request-row" onclick="go('requestDetail',{request:'${r.id}'})"><span class="request-ico">◌</span><span><strong>${r.title}</strong><small>${r.place} • ${r.offers} عروض</small></span></div>`).join('')}</div>${nav('home')}</section>`,
  search:()=>{ const q=state.query.trim(); const filtered=listings.filter(x=>(!state.category||x.cat===state.category)&&(!q||`${x.name} ${x.sub} ${x.city} ${x.cat}`.includes(q.replace('يمني','').replace('في','').trim())||q.split(' ').some(w=>w.length>2&&`${x.name} ${x.sub} ${x.city}`.includes(w)))); return `<section class="screen">${topbar('استكشف')}<div class="pad"><form class="search" onsubmit="event.preventDefault();state.query=this.q.value;render()"><span>⌕</span><input name="q" value="${state.query}" placeholder="مثال: مترجم يمني في نيودلهي"><button class="icon-btn" type="submit">←</button></form></div><div class="filters"><button class="chip">الدولة⌄</button><button class="chip">المدينة⌄</button><button class="chip" onclick="go('nearby')">◉ قريب مني</button></div><div class="categories">${categories.map(c=>`<button class="chip ${state.category===c[1]?'active':''}" onclick="state.category=state.category==='${c[1]}'?'':'${c[1]}';render()">${c[1]}</button>`).join('')}</div><div class="results-count">${filtered.length} نتائج مرتبة حسب الصلة</div><div class="pad">${filtered.length?filtered.map(listingCard).join(''):`<div class="empty"><b>لم نجد نتائج مطابقة</b>جرّب مدينة أخرى أو قلل عدد الفلاتر.</div>`}</div>${nav('search')}</section>`;},
  detail:()=>{ const x=listings.find(i=>i.id===state.selected)||listings[0]; return `<section class="screen"><div class="detail-hero"><img src="${x.image}" alt=""><button class="icon-btn back" onclick="go('search')">←</button></div><div class="detail-body"><div class="detail-title"><div style="flex:1"><h1>${x.name} <span class="verified">✓</span></h1><div>${x.sub}</div></div><span class="score">★ ${x.rating}</span></div><p>${x.reviews} تقييمًا • ${x.city}</p><div class="actions"><button class="primary" onclick="state.signed?go('chat'):go('account')">مراسلة</button><button class="minor" onclick="toast('سيُفتح واتساب في التطبيق الفعلي')">☎</button><button class="minor" onclick="toast('سيُفتح تطبيق الخرائط للاتجاهات')">➤</button></div><h2>نبذة</h2><p>${x.about}</p><div class="fact"><b>اللغات</b><span>${x.langs}</span></div><div class="fact"><b>منطقة الخدمة</b><span>${x.city}</span></div>${x.price?`<div class="fact"><b>السعر التقريبي</b><span>يبدأ من ${x.price} USD</span></div>`:''}<h2>آراء العملاء</h2><div class="offer-card"><strong>عبدالله أحمد　<span class="rating">★★★★★</span></strong><p>تواصل سريع وتعامل ممتاز، وكانت المعلومات في الصفحة دقيقة.</p></div></div></section>`;},
  nearby:()=>`<section class="screen">${topbar('قريب مني',true)}<div style="position:absolute;left:18px;top:11px;z-index:9" class="toggle"><button class="${!state.map?'active':''}" onclick="state.map=false;render()">قائمة</button><button class="${state.map?'active':''}" onclick="state.map=true;render()">خريطة</button></div>${state.map?`<div class="map">${[90,220,365,510].map((y,i)=>`<i class="road" style="top:${y}px"></i>`).join('')}<button class="pin" style="top:120px;right:65px">0.8 كم</button><button class="pin" style="top:280px;left:42px">1.4 كم</button><button class="pin" style="top:420px;right:130px">2.3 كم</button><div class="privacy">♢ نعرض المواقع العامة فقط، ومناطق خدمة تقريبية للأفراد.</div></div>`:`<div class="pad">${listings.filter(x=>x.distance).sort((a,b)=>a.distance-b.distance).map(listingCard).join('')}</div>`}</section>`,
  requests:()=>`<section class="screen">${topbar('طلبات الخدمات')}<div class="pad">${requests.map(r=>`<article class="request-card" onclick="go('requestDetail',{request:'${r.id}'})"><span class="badge">${r.offers} عروض</span><h3>${r.title}</h3><p>${r.desc}</p><div class="meta"><span>⌖ ${r.place}</span><span>${r.time}</span></div>${r.budget?`<div class="price">الميزانية: ${r.budget} USD</div>`:''}</article>`).join('')}</div><button class="fab" onclick="go('newRequest')">＋ نشر طلب</button>${nav('requests')}</section>`,
  newRequest:()=>`<section class="screen">${topbar('نشر طلب خدمة',true)}<form class="pad form" onsubmit="event.preventDefault();if(!state.signed){go('account');toast('سجّل الدخول أولًا لنشر الطلب')}else{toast('تم نشر طلبك بنجاح');go('requests')}"><label>عنوان الطلب</label><input required minlength="5" placeholder="مثال: أحتاج مصورًا في الرياض"><label>التفاصيل</label><textarea required minlength="10" placeholder="اشرح الوقت والمتطلبات المهمة"></textarea><div class="form-grid"><div><label>الدولة</label><select><option>السعودية</option><option>الهند</option><option>ماليزيا</option></select></div><div><label>المدينة</label><select><option>الرياض</option><option>نيودلهي</option><option>كوالالمبور</option></select></div></div><label>التصنيف</label><select><option>تصوير</option><option>ترجمة</option><option>سكن</option></select><label>الميزانية الاختيارية</label><input type="number" placeholder="USD"><button class="primary">نشر الطلب</button></form></section>`,
  requestDetail:()=>{const r=requests.find(i=>i.id===state.request)||requests[0];return `<section class="screen">${topbar('تفاصيل الطلب',true)}<div class="pad"><h1 style="font-size:25px">${r.title}</h1><p class="meta">⌖ ${r.place} • ${r.time}</p><p style="line-height:1.7">${r.desc}</p><div class="fact"><b>الميزانية</b><span>${r.budget||'مرنة'} USD</span></div><div class="section-head"><h2>${r.offers} عروض مقدمة</h2></div>${[['أروى الحكيمي','4.9','850'],['منار للإنتاج','4.8','980'],['عدنان الصبري','4.7','700']].map(o=>`<div class="offer-card"><div class="offer-head"><span class="avatar">${o[0][0]}</span><strong>${o[0]} <span class="verified">✓</span><small style="display:block;color:var(--muted)">★ ${o[1]} • تسليم خلال يومين</small></strong><span class="offer-price">${o[2]} USD</span></div></div>`).join('')}<button class="primary" onclick="state.signed?toast('تم إرسال العرض التجريبي'):go('account')">تقديم عرض</button></div></section>`;},
  offers:()=>`<section class="screen">${topbar('عروض اليوم',true)}<div class="pad">${[['خصم غداء العائلة','باب اليمن • الرياض','180','135','25%'],['شهر سكن للطلاب الجدد','سكن روافد • كوالالمبور','240','190','21%'],['شحن أول طرد','سبأ للشحن • نيويورك','90','65','28%']].map((o,i)=>`<div class="offer-card" style="${i===0?'background:var(--ink);color:white;border-color:var(--ink)':''}"><span class="badge" style="background:var(--coral);color:white">${o[4]}</span><h3>${o[0]}</h3><p>${o[1]}</p><strong style="font-size:22px">${o[3]} USD</strong>　<del>${o[2]} USD</del></div>`).join('')}</div></section>`,
  account:()=>`<section class="screen">${topbar('حسابي')}<div class="pad">${state.signed?`<div class="offer-head" style="margin:15px 0 26px"><span class="avatar" style="width:58px;height:58px">إ</span><strong>إبراهيم محمد<small style="display:block;color:var(--muted)">حساب مستخدم</small></strong></div>`:`<div class="offer-card" style="background:var(--ink);color:white;border-color:var(--ink);padding:20px"><h2 style="margin-top:0">استفد من كل المزايا</h2><p>سجّل لنشر طلب والتواصل وإدارة صفحاتك.</p><button class="primary" onclick="state.signed=true;toast('تم تسجيل الدخول التجريبي');render()">تسجيل الدخول التجريبي</button></div>`}${[['▣','منشآتي وصفحاتي'],['✓','التوثيق واستلام صفحة'],['◌','المحادثات'],['♢','تفضيلات الإشعارات'],['文','اللغة'],['⌾','الخصوصية والأمان']].map(i=>`<div class="request-row" onclick="${i[1]==='المحادثات'?(state.signed?"go('chat')":"toast('سجّل الدخول أولًا')"):"toast('هذه الشاشة مجهزة للربط في التطبيق')"}"><span class="request-ico">${i[0]}</span><strong style="flex:1">${i[1]}</strong><span>‹</span></div>`).join('')}</div>${nav('account')}</section>`,
  chat:()=>`<section class="chat">${topbar('أروى الحكيمي',true)}<div class="ref">◌ طلب: أحتاج مصورًا في الرياض</div><div class="messages" id="messages"><div class="bubble mine">مرحبًا، شاهدت عرضك على طلب التصوير.<small>10:24</small></div><div class="bubble">أهلًا بك. نعم، أنا متاحة يوم الجمعة ويمكنني إرسال نماذج أعمال إضافية.<small>10:26</small></div><div class="bubble mine">ممتاز، هل العرض يشمل فيديو قصير للفعالية؟<small>10:28</small></div></div><form class="composer" onsubmit="sendMessage(event)"><input name="msg" required placeholder="اكتب رسالة..."><button class="send">➤</button></form></section>`,
  notifications:()=>`<section class="screen">${topbar('الإشعارات',true)}<div class="pad">${[['◇','وصلك عرض جديد','قدمت أروى عرضًا على طلب التصوير.'],['◌','رسالة جديدة','لدي نماذج أعمال إضافية أرسلها لك.'],['✓','تم توثيق الصفحة','أصبحت صفحة باب اليمن موثقة.']].map(n=>`<div class="request-row"><span class="request-ico" style="background:var(--mint);color:var(--forest)">${n[0]}</span><span><strong>${n[1]}</strong><small>${n[2]}</small></span></div>`).join('')}</div></section>`
};
function sendMessage(e){e.preventDefault();const input=e.target.msg;if(!input.value.trim())return;const box=document.querySelector('#messages');box.insertAdjacentHTML('beforeend',`<div class="bubble mine">${input.value.replace(/[<>]/g,'')}<small>الآن</small></div>`);input.value='';}
render();
